config/routes.rb
JobTracker::Application.routes.draw do

  root to: 'jobs#index'

  resources :jobs, :cities, :companies, :technologies

end

app/models/city.rb
class City < ActiveRecord::Base
  has_and_belongs_to_many :jobs
  attr_accessible :name, :coolness_factor
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :jobs
  attr_accessible :name, :website_url, :description, :sarah_thoughts,
    :coolness_factor
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :company
  has_and_belongs_to_many :cities
  has_and_belongs_to_many :technologies
  attr_accessible :company_id, :title, :application_url, :description,
    :challenge_factor, :likelihood_factor, :travel_percentage, :applied,
    :requires_cover_letter, :requires_long_application, :city_ids,
    :technology_ids

  def city_names
    cities.map(&:name).join ', '
  end

  def technology_names
    technologies.map(&:name).join ', '
  end
end

app/models/technology.rb
class Technology < ActiveRecord::Base
  has_and_belongs_to_many :jobs
  attr_accessible :name, :coolness_factor, :current_expertise
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

    def index
    end

    def show
    end

    def new
    end

    def create
      @city = City.create(params[:city])
      respond_to do |f|
        f.html { redirect_to root_path }
        f.json { render :json => @city }
      end
    end

    def update
    end

    def delete
    end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

    def index
    end

    def show
    end

    def new
    end

    def create
      @company = Company.create(params[:company])
      respond_to do |f|
        f.html { redirect_to root_path }
        f.json { render :json => @company }
      end
    end

    def update
    end

    def delete
    end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

    def index
      # @jobs = Job.order("challenge_factor DESC, likelihood_factor DESC")
      @jobs = Job.includes(:company, :technologies, :cities).all
    end

    def show
      @job = Job.find(params[:id])
    end

    def new
      @job = Job.new
    end

    def create
      @job = Job.create(params[:job])
      respond_to do |f|
        f.html { redirect_to @job }
        f.json { render :json => @job }
      end
    end

    def edit
      @job = Job.find(params[:id])
    end

    def update
      @job = Job.find(params[:id])
      respond_to do |format|
        if @job.update_attributes(params[:job])
          format.html  { redirect_to @job }
          format.json  { head :no_content }
        else
          format.html  { render :action => "edit" }
          format.json  { render :json => @job.errors,
                         :status => :unprocessable_entity }
        end
      end
    end

    def delete
    end

end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController

    def index
    end

    def show
    end

    def new
    end

    def create
      @technology = Technology.create(params[:technology])
      respond_to do |f|
        f.html { redirect_to root_path }
        f.json { render :json => @technology }
      end
    end

    def update
    end

    def delete
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobs/_form.html.erb
<div class="row">
  <%= simple_form_for @job do |f| %>
    <div class="span6">
      <%= f.input :title, input_html: { class: 'span6' } %>
      <%= f.input :description, input_html: { rows: 3, class: 'span6' } %>
      <%= f.input :application_url, label: "Application URL", input_html: { class: 'span6' } %>
      <div class="row">
        <div class="span3">
          <%= f.association :cities %>
          <input type="text" id="new_city" placeholder="Add a city..." /><br />
          <a class="btn" id="add_city_button">Add city</a><br /><br />
        </div>
        <div class="span3">
          <%= f.association :technologies %>
          <input type="text" id="new_technology" placeholder="Add a technology..." /><br />
          <a class="btn" id="add_technology_button">Add technology</a><br /><br />
        </div>
      </div>
    </div>
    <div class="span3">
      <%= f.association :company, include_blank: false %>
      <input type="text" id="new_company" placeholder="Add a company..." /><br />
      <a class="btn" id="add_company_button">Add company</a><br /><br />
      <%= f.input :requires_cover_letter %>
      <%= f.input :requires_long_application %>
      <%= f.input :challenge_factor, :wrapper => :append do %>
        <%= f.input_field :challenge_factor, class: 'span1' %>
        <span class="add-on">%</span>
      <% end %>
      <%= f.input :likelihood_factor, :wrapper => :append do %>
        <%= f.input_field :likelihood_factor, class: 'span1' %>
        <span class="add-on">%</span>
      <% end %>
      <%= f.input :travel_percentage, :wrapper => :append do %>
        <%= f.input_field :travel_percentage, class: 'span1' %>
        <span class="add-on">%</span>
      <% end %>
    </div>
    <div class="span3">
      <%= f.button :submit, class: 'btn btn-primary btn-large' %>
    </div>
  <% end %>
</div>

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>
<%= render 'form'%>

app/views/jobs/index.html.erb
<table class="table table-striped table-hover table-condensed datatable">
  <thead>
    <th>Company</th>
    <th>Title</th>
    <th>Cities</th>
    <th>Technologies</th>
    <th>Challenge</th>
    <th>Likelihood</th>
    <th>Applied?</th>
    <th>Cover Letter?</th>
    <th>Long App?</th>
  </thead>
  <tbody>
    <% @jobs.each do |j| %>
      <tr rel="<%= job_path j %>">
        <td><%= j.company.name %></td>
        <td><%= j.title %></td>
        <td><%= j.city_names %></td>
        <td><%= j.technology_names %></td>
        <td><%= j.challenge_factor %>%</td>
        <td><%= j.likelihood_factor %>%</td>
        <td><%= j.applied ? "Yes" : "No" %></td>
        <td><%= j.requires_cover_letter ? "Yes" : "No" %></td>
        <td><%= j.requires_long_application ? "Yes" : "No" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/new.html.erb
<h1>Add a Job</h1>
<%= render 'form'%>

app/views/jobs/show.html.erb
<div class="row">
  <div class="span12">
    <h1><%= @job.title %> at <%= link_to@job.company.name, @job.company %></h1>
    <div class="row">
      <div class="span9">
        <%= simple_format @job.description %>
        <br />
        <% unless @job.applied %>
          <%= link_to "Apply here", @job.application_url, class: "btn btn-primary" %>
        <% end %>
        <%= link_to "Edit Job", edit_job_path(@job), class: "btn" %>
      </div>
      <div class="span3">
        Technologies
        <ul>
          <% @job.technologies.each do |t| %>
            <li><%= t.name %></li>
        <% end %>
        </ul>

        Cities
        <ul>
          <% @job.cities.each do |t| %>
            <li><%= t.name %></li>
        <% end %>
        </ul>

        <p>
          <strong>Cover letter?</strong>
          <%= @job.requires_cover_letter ? "Yes" : "No" %><br />
          <strong>Long application?</strong>
          <%= @job.requires_long_application ? "Yes" : "No" %>
        </p>
        <p>
          <strong>Challenge:</strong> <%= @job.challenge_factor %>%<br />
          <strong>Likelihood:</strong> <%= @job.likelihood_factor %>%<br />
          <strong>Travel:</strong> <%= @job.travel_percentage %>%<br />
        </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<title>JobTracker</title>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<style>
  body {
    padding-top: 60px;
    padding-bottom: 40px;
  }
</style>
</head>
<body>
<div class="container">
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a href="<%= root_path %>" class="brand">Job Tracker</a>
        <ul class="nav">
          <li class="active">
            <a href="<%= jobs_path %>">Jobs</a>
          </li>
          <li>
            <a href="<%= new_job_path %>">Add a Job</a>
          </li>
          <li>
            <a href="<%= companies_path %>">Companies</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <%= yield %>
    </div> <%# end span9 %>
  </div> <%# end row %>
</div> <%# end container %>
</body>
</html>